# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendfriend', to='login_reg.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userfriend', to='login_reg.User')),
            ],
        ),
    ]
