# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0002_remove_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='2016-08-25'),
            preserve_default=False,
        ),
    ]
